name: nox-plugin-container
version: 0.1.0
track: core-analysis
description: Dockerfile security linting and container image analysis for misconfigurations and best practices
tools:
  - name: scan
    description: Scan Dockerfiles for security misconfigurations and best practice violations
